<p><img src="https://raw.githubusercontent.com/trinker/regextools/master/inst/regextools_logo/r_regextools.png" width="100", height="100"/><br/>
<p><a href="http://trinker.github.com/regextools_dev">regextools</a> extends the <strong>devtools</strong>, <strong>roxygen2</strong>, &amp; <strong>testthat</strong> packages to regular expressions library documentation, testing, and storage.  The framework assumes the user will document and store regular expressions as an R package via the <strong>devtools</strong>, <strong>roxygen2</strong>, &amp; <strong>testthat</strong> packages.  This extends these existing frameworks to work make regular expression management easier for long term documentation, maintenance, and 
testing.  The only change to these existing frameworks is that the user must include a tag <code>@section Regex: TRUE</code> in the <strong>roxygen2</strong> markup, indicating the object is a regular expression.  </p>

<p><strong>regextools</strong> is a philosophy of regular expression management that sees unit testing and transparency of test coverage as an essential part of maintaining a regular expression library.  In the spirit of transparent unit testing, <strong>regextools</strong> adds functions to test regular expressions, extending the <strong>testthat</strong> package.  This avoids unforeseen breaks due to changes in a regular expression and explicitally describes the expression&#39;s intended behavior.  <strong>regextools</strong> offers a template system that encourages this transparent unit testing philosophy through the use of <a href="https://github.com/">GitHub</a>, <a href="https://travis-ci.org">Travis-CI</a>, and the <a href="https://github.com/jimhester/covr"><strong>covr</strong></a> package to indicate coverage in the GitHub README.md.  </p>

<p><strong>regextools</strong> also highlights the need for minimal, clear, description of a regular expression&#39;s behavior.  <strong>regextools</strong> provides tools to generate html, .md, and .Rmd vignettes from existing <strong>roxygen2</strong> markup rather than the more verbose package help documentation.  Regular expressions are often difficult to parse, particularly as the expression&#39;s complexity grows.  Visual presentation of the regular expression can enhance the maintainer and user&#39;s abilities to understand the expression&#39;s design.  <strong>regextools</strong> includes a link/iframe of <a href="https://www.debuggex.com">Debuggex&#39;s</a> terrific visual diagram representation of regular expressions.  </p>
    
<h3>Development Version</h3>    
<p>Download the development version of regextools <a href="https://github.com/trinker/regextools/">here</a> 